services:
  - type: static
    name: flutter-web
    root: .
    buildCommand: |
      curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.2-stable.tar.xz
      tar xf flutter_linux_3.22.2-stable.tar.xz
      export PATH="$PATH:$(pwd)/flutter/bin"
      flutter config --enable-web
      flutter build web --release
    publish: build/web
